<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

/**
 * LandClassificationSeeder
 *
 * Insere terrenos de exemplo para todas as 4 classificações:
 *   - urbanos          → área em ha (urbanizáveis / habitacionais)
 *   - rusticos         → área em ha (agrícola / florestal / pastagem)
 *   - industriais      → área em ha (logística / polo industrial)
 *   - projecto-aprovado → área em ha (com projecto e licença)
 *
 * REGRA: terrenos são sempre medidos em hectares (ha).
 */
class LandClassificationSeeder extends Seeder
{
    public function run(): void
    {
        $terrenos = [

            // ================================================================
            // URBANOS
            // ================================================================
            [
                'title'         => 'Terreno Urbano — Benfica, Luanda',
                'description'   => 'Excelente terreno urbano em zona residencial consolidada no Benfica. Infraestruturas completas de água, eletricidade e acessos asfaltados. Ideal para construção de moradia de luxo, condomínio fechado ou prédio de apartamentos de pequeno/médio porte.',
                'price'         => '55.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'urbanos',
                'country'       => 'Angola',
                'city'          => 'Luanda',
                'location'      => 'Benfica, Luanda',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '1,2 ha',
                'image'         => '3.jpeg',
                'gallery'       => ['1.jpeg', '2.jpeg'],
                'amenities'     => ['Acesso Asfaltado', 'Rede Elétrica', 'Água Canalizada', 'Vedado', 'Zona Residencial Consolidada'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno Urbano — Talatona, Luanda',
                'description'   => 'Terreno urbano de grande dimensão em Talatona, zona nobre de Luanda Sul. Topografia plana, totalmente vedado e com todas as infraestruturas de saneamento disponíveis. Viabilidade para condomínio residencial ou centro comercial.',
                'price'         => '180.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'urbanos',
                'country'       => 'Angola',
                'city'          => 'Luanda',
                'location'      => 'Talatona, Luanda Sul',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '3,5 ha',
                'image'         => '1.jpeg',
                'gallery'       => ['2.jpeg', '3.jpeg'],
                'amenities'     => ['Zona Nobre', 'Topografia Plana', 'Vedado', 'Rede de Saneamento', 'Acesso Asfaltado'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno Urbano — Quelimane, Huambo',
                'description'   => 'Terreno urbano em expansão na cidade do Huambo. Localizado em bairro em crescimento acelerado, com infraestruturas básicas disponíveis. Excelente para investimento imobiliário de longa duração.',
                'price'         => '18.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'urbanos',
                'country'       => 'Angola',
                'city'          => 'Huambo',
                'location'      => 'Bairro Académico, Huambo',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '0,8 ha',
                'image'         => '2.jpeg',
                'gallery'       => ['1.jpeg'],
                'amenities'     => ['Zona em Expansão', 'Rede Elétrica', 'Acesso por Via Principal'],
                'is_featured'   => false,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno Urbano — Lobito, Benguela',
                'description'   => 'Terreno urbano no Lobito, cidade portuária com crescimento acelerado. Situado em zona mista residencial-comercial, junto de vias estruturantes. Plano e de fácil acesso — ideal para desenvolvimento de condomínio horizontal.',
                'price'         => '32.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'urbanos',
                'country'       => 'Angola',
                'city'          => 'Benguela',
                'location'      => 'Lobito, Benguela',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '1,8 ha',
                'image'         => '1.jpeg',
                'gallery'       => ['2.jpeg'],
                'amenities'     => ['Zona Mista', 'Topografia Plana', 'Acesso por Via Asfaltada', 'Rede de Água'],
                'is_featured'   => false,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],

            // ================================================================
            // RÚSTICOS
            // ================================================================
            [
                'title'         => 'Terreno Rústico Agrícola — Quibala, Cuanza Sul',
                'description'   => 'Vasta extensão de terreno rústico para exploração agrícola e pecuária no Cuanza Sul. Solos férteis de tipo ferrálico, ribeira com água permanente durante todo o ano e excelente exposição solar. Ideal para culturas de milho, girassol, mandioca e criação de gado.',
                'price'         => '120.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'rusticos',
                'country'       => 'Angola',
                'city'          => 'Cuanza Sul',
                'location'      => 'Quibala, Cuanza Sul',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '50 ha',
                'image'         => '2.jpeg',
                'gallery'       => ['1.jpeg', '3.jpeg'],
                'amenities'     => ['Furo de Água', 'Solo Fértil', 'Acesso a Ribeira', 'Pastagem Natural'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Herdade Rústica para Agricultura — Malanje',
                'description'   => 'Extensão de terreno rústico apto para cultivo intensivo em Malanje, o celeiro de Angola. Solo fértil com elevada capacidade de retenção de humidade. Acesso a estrada provincial com caminho de terra batida até ao terreno. Inclui antiga casa de apoio agrícola.',
                'price'         => '280.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'rusticos',
                'country'       => 'Angola',
                'city'          => 'Malanje',
                'location'      => 'Cacuso, Malanje',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '120 ha',
                'image'         => '3.jpeg',
                'gallery'       => ['1.jpeg', '2.jpeg'],
                'amenities'     => ['Solo Fértil', 'Curso de Água', 'Casa de Apoio', 'Acesso Rodoviário', 'Eletricidade Próxima'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno Rústico de Pastagem — Cuando Cubango',
                'description'   => 'Imponente terreno rústico no sul de Angola, na região do Cuando Cubango, com vocação para pecuária extensiva. Savanas abertas com excelente cobertura de pastagem natural e ponto de água permanente. Acesso por pista de terra batida.',
                'price'         => '95.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'rusticos',
                'country'       => 'Angola',
                'city'          => 'Cuando Cubango',
                'location'      => 'Menongue, Cuando Cubango',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '350 ha',
                'image'         => '1.jpeg',
                'gallery'       => ['2.jpeg'],
                'amenities'     => ['Pastagem Natural', 'Ponto de Água Permanente', 'Savana Aberta', 'Boa Exposição Solar'],
                'is_featured'   => false,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Quinta Rústica — Alentejo, Portugal',
                'description'   => 'Quinta rústica no coração do Alentejo, com sobreiros e azinheiras em regime de montado. Terreno com aprovação para exploração agrícola e cinegética. Perto da Herdade do Esporão. Ideal para ecoturismo ou produção de cortiça e azeite.',
                'price'         => '1.200.000 EUR',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'rusticos',
                'country'       => 'Portugal',
                'city'          => 'Évora',
                'location'      => 'Reguengos de Monsaraz, Alentejo',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '85 ha',
                'image'         => '2.jpeg',
                'gallery'       => ['1.jpeg', '3.jpeg'],
                'amenities'     => ['Montado de Sobreiros', 'Exploração Cinegética', 'Charca', 'Furo Artesiano', 'Casas de Apoio'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],

            // ================================================================
            // INDUSTRIAIS
            // ================================================================
            [
                'title'         => 'Terreno Industrial — Polo de Viana, Luanda',
                'description'   => 'Terreno industrial de grande porte no Polo Industrial de Viana, o principal centro de logística industrial de Luanda. Acesso direto à estrada nacional e a vias rápidas de transporte de mercadorias. Infraestrutura elétrica de alta tensão disponível no lote.',
                'price'         => '180.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'industriais',
                'country'       => 'Angola',
                'city'          => 'Luanda',
                'location'      => 'Polo Industrial de Viana, Luanda',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '15 ha',
                'image'         => '1.jpeg',
                'gallery'       => ['2.jpeg', '3.jpeg'],
                'amenities'     => ['Zona Industrial', 'Alta Tensão Elétrica', 'Acesso a Camiões TIR', 'Próximo de Porto Seco'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Lote Industrial para Armazém — Catete, Bengo',
                'description'   => 'Terreno industrial situado na zona de expansão industrial do Bengo, com excelente acessibilidade ao Porto de Luanda e ao aeroporto internacional. Adequado para armazém, unidade de processamento alimentar ou indústria ligeira.',
                'price'         => '75.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'industriais',
                'country'       => 'Angola',
                'city'          => 'Bengo',
                'location'      => 'Catete, Bengo',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '8 ha',
                'image'         => '3.jpeg',
                'gallery'       => ['1.jpeg'],
                'amenities'     => ['Indústria Ligeira', 'Acesso Porto de Luanda', 'Rede de Alta Tensão', 'Vedado e Murado'],
                'is_featured'   => false,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno Industrial — Setúbal, Portugal',
                'description'   => 'Lote industrial em zona de uso misto industrial e logístico em Setúbal, com ligação direta à A2 e ao porto fluvial do Sado. Já tem PDM aprovado para construção de pavilhão industrial de grande porte. Infraestruturas completas.',
                'price'         => '3.500.000 EUR',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'industriais',
                'country'       => 'Portugal',
                'city'          => 'Setúbal',
                'location'      => 'Zona Industrial de Setúbal',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '22 ha',
                'image'         => '2.jpeg',
                'gallery'       => ['1.jpeg', '3.jpeg'],
                'amenities'     => ['PDM Aprovado', 'Acesso A2', 'Rede de Alta Tensão', 'Água Industrial', 'Esgotos Industriais'],
                'is_featured'   => false,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno Industrial Logístico — Gauteng, África do Sul',
                'description'   => 'Terreno industrial prime na zona de Gauteng, um dos maiores polos logísticos da África Subsaariana. Servido por ligação ferroviária e rodoviária. Adequado para parque de distribuição, centro de dados ou unidade de fabrico de escala regional.',
                'price'         => '28.000.000 ZAR',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'industriais',
                'country'       => 'África do Sul',
                'city'          => 'Gauteng',
                'location'      => 'Kempton Park, Gauteng',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '45 ha',
                'image'         => '1.jpeg',
                'gallery'       => ['2.jpeg', '3.jpeg'],
                'amenities'     => ['Ligação Ferroviária', 'Alta Tensão', 'Zona de Livre Comércio', 'Acesso Aeroporto OR Tambo'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],

            // ================================================================
            // PROJECTO APROVADO
            // ================================================================
            [
                'title'         => 'Terreno com Projecto Aprovado — Talatona, Luanda',
                'description'   => 'Terreno de grande prestígio em Talatona com projecto de arquitectura aprovado para a construção de edifício residencial/comercial de 4 pisos. Licenças pagas e tudo pronto para início de obras imediato. Localização premium em zona de alta procura.',
                'price'         => '250.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'projecto-aprovado',
                'country'       => 'Angola',
                'city'          => 'Luanda',
                'location'      => 'Talatona Sul, Luanda',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '2,5 ha',
                'image'         => '3.jpeg',
                'gallery'       => ['1.jpeg', '2.jpeg'],
                'amenities'     => ['Projecto Aprovado', 'Licença de Construção', 'Zona Nobre', 'Topografia Regular', 'Infraestruturas Completas'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno c/ Projecto Hoteleiro Aprovado — Ilha do Mussulo, Luanda',
                'description'   => 'Raro terreno na Ilha do Mussulo com projecto turístico aprovado para construção de hotel boutique de 5 estrelas com 40 suítes e marina privada. Todos os estudos de impacto ambiental concluídos e aprovados. Oportunidade única de investimento turístico.',
                'price'         => '500.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'projecto-aprovado',
                'country'       => 'Angola',
                'city'          => 'Luanda',
                'location'      => 'Ilha do Mussulo, Luanda',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '4,2 ha',
                'image'         => '2.jpeg',
                'gallery'       => ['1.jpeg', '3.jpeg'],
                'amenities'     => ['Projecto Hoteleiro Aprovado', 'Frente de Praia', 'Estudo Ambiental Concluído', 'Marina Incluída', 'Exclusividade Turística'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno c/ Projecto Residencial Aprovado — Benguela',
                'description'   => 'Terreno com projecto aprovado para condomínio fechado de 60 moradias em Benguela. Infra-estruturas de água e energia aprovadas pelo município. Projecto arquitectónico e engenharia civil concluídos. Pronto para contratação de empreitada.',
                'price'         => '95.000.000 Kz',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'projecto-aprovado',
                'country'       => 'Angola',
                'city'          => 'Benguela',
                'location'      => 'Zona Residencial Norte, Benguela',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '6 ha',
                'image'         => '1.jpeg',
                'gallery'       => ['2.jpeg', '3.jpeg'],
                'amenities'     => ['Projecto Aprovado', '60 Lotes Residenciais', 'Projecto de Engenharia', 'Licença Municipal', 'Infraestruturas Aprovadas'],
                'is_featured'   => false,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
            [
                'title'         => 'Terreno c/ Projecto Comercial Aprovado — Lisboa, Portugal',
                'description'   => 'Terreno em Lisboa com projecto aprovado para a construção de parque empresarial com 8 pavilhões modulares e zona de coworking. Situado na Margem Sul em zona com incentivos fiscais. Projecto de arquitectura de renome nacional.',
                'price'         => '4.800.000 EUR',
                'price_period'  => null,
                'type'          => 'venda',
                'category'      => null,
                'property_type' => 'terreno',
                'land_type'     => 'projecto-aprovado',
                'country'       => 'Portugal',
                'city'          => 'Lisboa',
                'location'      => 'Barreiro, Margem Sul, Lisboa',
                'bedrooms'      => 0,
                'bathrooms'     => 0,
                'garages'       => 0,
                'area'          => '12 ha',
                'image'         => '3.jpeg',
                'gallery'       => ['1.jpeg', '2.jpeg'],
                'amenities'     => ['Projecto Aprovado CML', 'Incentivos Fiscais', 'Parque Empresarial', 'Acesso Ferroviário', 'Ligação Fertagus'],
                'is_featured'   => true,
                'is_active'     => true,
                'status'        => 'disponivel',
            ],
        ];

        foreach ($terrenos as $data) {
            Property::firstOrCreate(
                ['title' => $data['title']],
                $data
            );
        }

        $this->command->info('✅ LandClassificationSeeder concluído: ' . count($terrenos) . ' terrenos inseridos/verificados.');
        $this->command->table(
            ['Classificação', 'Total'],
            [
                ['Urbanos',           count(array_filter($terrenos, fn($t) => $t['land_type'] === 'urbanos'))],
                ['Rústicos',          count(array_filter($terrenos, fn($t) => $t['land_type'] === 'rusticos'))],
                ['Industriais',       count(array_filter($terrenos, fn($t) => $t['land_type'] === 'industriais'))],
                ['Projecto Aprovado', count(array_filter($terrenos, fn($t) => $t['land_type'] === 'projecto-aprovado'))],
            ]
        );
    }
}
